### ISSUE TITLE
ACPDFVIEW - acknowledgement

### ISSUE THREAD

**Issue by alanliska** [Bhuvaneshw/acpdfview#1]
Dear Sir,

me and my friend Veronika Ruzickova focus at porting professional open-source chemistry codes to Android. Recently, we have published 3 new free apps:
PHREEQC plus
https://play.google.com/store/apps/details?id=cz.p
https://github.com/alanliska/PHREEQC-plus
DFTB+
https://play.google.com/store/apps/details?id=cz.jh.dftb
https://github.com/alanliska/DFTB
XTB
https://play.google.com/store/apps/details?id=cz.jh.xtb
https://github.com/alanliska/XTB
where we utilized your BRILLIANT library 'acpdfview' for displaying the manuals in the apps. Because we plan to upgrade also some other similar apps, it is highly probable that we integrate your 'acpdfview' to them as well.
Inside of each app as well as in the individual package descriptions, we cited your software as follows:

 * ACPDFVIEW
 Author: Bhuvaneshw (Github)
 Source code: https://github.com/Bhuvaneshw/acpdfview
 License: GNU GPL-3.0

Please let me know if you would like to enhance the reference to you, or specify the citation in a more detailed way.
Thank you.

Sincerely,

Alan

-- 
RNDr. Alan Liška, Ph.D.
Ústav fyzikální chemie J. Heyrovského AV ČR, v.v.i. / J. Heyrovský Institute of Physical Chemistry of the CAS, v.v.i.
Dolejškova 3/2155, 18223 Praha 8
Česká republika / Czech Republic

**Comment by Bhuvaneshw** [comment]
Thank you for using my open source project. Everything is ok. Just change my name to Bhuvaneshwaran.

ACPDFVIEW
Author: Bhuvaneshwaran (Github)
Source code: https://github.com/Bhuvaneshw/acpdfview
License: GNU GPL-3.0

**Comment by alanliska** [comment]
Thank you as well, I did the change in all apps and their sources.
